### ISSUE TITLE
data and readme file

### ISSUE THREAD

**Issue by dshizuka** [AlondraDelmar/BIOS967_Torres#1]
Hi Alondra, 
I know you are having your procedure early next week, so the data and readme file stuff can wait until you are feeling recovered enough for it. Just let me know when you've been able to get those uploaded so that I can know to take a look.

**Comment by AlondraDelmar** [comment]
I apologize profesor,  just saw your email.
I was thinkiNg of using some data from my previous lab rotation but it’s
not published so I will make it private. It’s MS data.
I had my surgery yesterday I’m in recovery but I’ll make sure to said the
data to you. I apologize for they inconvenience.

Thank you so much 😊
Alondra
